development:
  adapter: postgresql
  encoding: unicode
  database: yelp_development
  pool: 5
  username: taylorpeat
  password: YOUR_PASSWORD

test:
  adapter: postgresql
  encoding: unicode
  database: yelp_test
  pool: 5
  username: taylorpeat
  password: YOUR_PASSWORD
